name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "final-eklemeler" ]
  pull_request:
    branches: [ "main", "final-eklemeler" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # Backend
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install Backend Dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Check Backend Syntax
      run: |
        cd backend
        python -m py_compile main.py models.py schemas.py database.py

    # Frontend
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install
        
    - name: Build Frontend
      run: |
        cd frontend
        npm run build
