name: Run Playwright Tests

on:
  push:
    branches: [ main, final-eklemeler ]
  pull_request:
    branches: [ main, final-eklemeler ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Install Playwright browsers
        run: |
          cd frontend
          npx playwright install

      - name: Run tests
        run: |
          cd frontend
          npx playwright test